version: '3'

networks:
  my_network:
    external: true
    driver: bridge

services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: opssvc_postgres_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./src/main/resources/initdb/init1-opssvcdb-schema.sql:/docker-entrypoint-initdb.d/init1-opssvcdb-schema.sql
      - ./src/main/resources/initdb/init2-opssvcdb-data.sql:/docker-entrypoint-initdb.d/init2-opssvcdb-data.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  opssvc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50020:50020"
      - "50025:50025"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - my_network

volumes:
  postgres_data: